// ABIs for gitlawb protocol contracts. Hand-curated — only the functions
// the frontend actually calls, to keep bundles small.

export const ERC20_ABI = [
  { type: "function", name: "balanceOf", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable",
    inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
] as const;

export const STAKING_ABI = [
  { type: "function", name: "stake", stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "requestUnstake", stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "unstake", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "claimRewards", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "getStakeInfo", stateMutability: "view",
    inputs: [{ name: "staker", type: "address" }],
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "tier", type: "uint8" },
      { name: "multiplier", type: "uint256" },
      { name: "pendingRewards", type: "uint256" },
      { name: "unstakeRequestAt", type: "uint256" },
      { name: "unstakeAmount", type: "uint256" },
    ] },
  { type: "function", name: "pendingRewards", stateMutability: "view",
    inputs: [{ name: "staker", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalStaked", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalRewardsDistributed", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getProtocolStats", stateMutability: "view", inputs: [],
    outputs: [
      { name: "totalStaked", type: "uint256" },
      { name: "totalWeightedStake", type: "uint256" },
      { name: "totalRewardsDistributed", type: "uint256" },
      { name: "accRewardPerShare", type: "uint256" },
    ] },
] as const;

export const NODE_STAKING_ABI = [
  { type: "function", name: "registerNode", stateMutability: "nonpayable",
    inputs: [
      { name: "nodeDidHash", type: "bytes32" },
      { name: "httpUrl", type: "string" },
      { name: "stakeAmount", type: "uint256" },
    ], outputs: [] },
  { type: "function", name: "heartbeat", stateMutability: "nonpayable",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "requestUnstake", stateMutability: "nonpayable",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "unstake", stateMutability: "nonpayable",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "claimRewards", stateMutability: "nonpayable",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "updateHttpUrl", stateMutability: "nonpayable",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }, { name: "httpUrl", type: "string" }], outputs: [] },
  { type: "function", name: "getNodeInfo", stateMutability: "view",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }],
    outputs: [
      { name: "operator", type: "address" },
      { name: "httpUrl", type: "string" },
      { name: "stake", type: "uint256" },
      { name: "lastHeartbeat", type: "uint256" },
      { name: "registeredAt", type: "uint256" },
      { name: "active", type: "bool" },
      { name: "currentlyActive", type: "bool" },
      { name: "pendingRewards", type: "uint256" },
      { name: "unstakeRequestAt", type: "uint256" },
    ] },
  { type: "function", name: "pendingRewards", stateMutability: "view",
    inputs: [{ name: "nodeDidHash", type: "bytes32" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getProtocolStats", stateMutability: "view", inputs: [],
    outputs: [
      { name: "totalRegisteredStake", type: "uint256" },
      { name: "totalActiveStake", type: "uint256" },
      { name: "totalRewardsDistributed", type: "uint256" },
      { name: "accRewardPerShare", type: "uint256" },
      { name: "nodeCount", type: "uint256" },
    ] },
  { type: "function", name: "nodeCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "nodeIds", stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "MIN_STAKE", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalActiveStake", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalRegisteredStake", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
] as const;

export const FEE_DISTRIBUTOR_ABI = [
  { type: "function", name: "distribute", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "nextDistributionAt", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "pendingBalance", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "previewDistribution", stateMutability: "view", inputs: [],
    outputs: [
      { name: "total", type: "uint256" },
      { name: "nodeShare", type: "uint256" },
      { name: "userShare", type: "uint256" },
      { name: "keeperShare", type: "uint256" },
    ] },
  { type: "function", name: "nodeShareBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "userShareBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "keeperShareBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lastDistribution", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "distributionCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalDistributed", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "event", name: "FeesDistributed",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "total", type: "uint256", indexed: false },
      { name: "nodeShare", type: "uint256", indexed: false },
      { name: "userShare", type: "uint256", indexed: false },
      { name: "keeperShare", type: "uint256", indexed: false },
      { name: "keeper", type: "address", indexed: true },
    ],
    anonymous: false },
] as const;
